{{ if .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}-configmap
data:
  cerebro.conf: |-
{{ .Values.configMap.configFile | indent 4 }}
{{- end }}
